### PR TITLE
Improve README readability

### PR DESCRIPTION
**Pull request by nodunayo**

### CODE REVIEW

**Comment by andrew** [comment]
Thanks! My 2am grammar isn't the best 🙈

**Comment by nodunayo** [comment]
Ahaha, no worries. I'm always a little anxious about making such changes but I'm a stickler for it. :P

**Comment by andrew** [comment]
Feel free to make similar changes to the 24pr and libraries.io readmes 😉

**Comment by nodunayo** [comment]
Got it. ;-)

**Pull request merged**
